# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\Tools\Panasert\MainWindows.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 618)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 618))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 618))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setStatusTip("")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 1001, 61))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 6, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 10, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        self.BtnConnect = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.BtnConnect.setMinimumSize(QtCore.QSize(100, 40))
        self.BtnConnect.setMaximumSize(QtCore.QSize(100, 40))
        self.BtnConnect.setObjectName("BtnConnect")
        self.gridLayout.addWidget(self.BtnConnect, 1, 9, 1, 1)
        self.labelIPAddr = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelIPAddr.setObjectName("labelIPAddr")
        self.gridLayout.addWidget(self.labelIPAddr, 1, 1, 1, 1)
        self.lineEditIP = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditIP.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditIP.sizePolicy().hasHeightForWidth())
        self.lineEditIP.setSizePolicy(sizePolicy)
        self.lineEditIP.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEditIP.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEditIP.setWhatsThis("")
        self.lineEditIP.setInputMask("")
        self.lineEditIP.setText("")
        self.lineEditIP.setMaxLength(15)
        self.lineEditIP.setCursorPosition(0)
        self.lineEditIP.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditIP.setPlaceholderText("")
        self.lineEditIP.setObjectName("lineEditIP")
        self.gridLayout.addWidget(self.lineEditIP, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 5, 1, 1)
        self.lineEditPort = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditPort.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPort.sizePolicy().hasHeightForWidth())
        self.lineEditPort.setSizePolicy(sizePolicy)
        self.lineEditPort.setMinimumSize(QtCore.QSize(100, 40))
        self.lineEditPort.setMaximumSize(QtCore.QSize(100, 40))
        self.lineEditPort.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditPort.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditPort.setInputMask("")
        self.lineEditPort.setText("")
        self.lineEditPort.setMaxLength(5)
        self.lineEditPort.setCursorPosition(0)
        self.lineEditPort.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditPort.setObjectName("lineEditPort")
        self.gridLayout.addWidget(self.lineEditPort, 1, 7, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 8, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 140, 1001, 451))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 5, 0, 5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget_3)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setObjectName("tableWidget")
        self.gridLayout_3.addWidget(self.tableWidget, 2, 0, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 590, 1002, 30))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelModel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelModel.setEnabled(False)
        self.labelModel.setAlignment(QtCore.Qt.AlignCenter)
        self.labelModel.setObjectName("labelModel")
        self.verticalLayout.addWidget(self.labelModel)
        self.lineTitle_3 = QtWidgets.QFrame(self.centralwidget)
        self.lineTitle_3.setGeometry(QtCore.QRect(0, 129, 1000, 16))
        self.lineTitle_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineTitle_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineTitle_3.setObjectName("lineTitle_3")
        self.lineModel = QtWidgets.QFrame(self.centralwidget)
        self.lineModel.setGeometry(QtCore.QRect(0, 590, 1000, 3))
        self.lineModel.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineModel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineModel.setObjectName("lineModel")
        self.lineTitle = QtWidgets.QFrame(self.centralwidget)
        self.lineTitle.setGeometry(QtCore.QRect(0, 1, 1000, 16))
        self.lineTitle.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineTitle.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineTitle.setObjectName("lineTitle")
        self.lineTitle_2 = QtWidgets.QFrame(self.centralwidget)
        self.lineTitle_2.setGeometry(QtCore.QRect(0, 65, 1000, 16))
        self.lineTitle_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineTitle_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineTitle_2.setObjectName("lineTitle_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 80, 1001, 51))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 2, 1, 1)
        self.comboBoxOrders = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxOrders.sizePolicy().hasHeightForWidth())
        self.comboBoxOrders.setSizePolicy(sizePolicy)
        self.comboBoxOrders.setMinimumSize(QtCore.QSize(100, 30))
        self.comboBoxOrders.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBoxOrders.setCurrentText("")
        self.comboBoxOrders.setObjectName("comboBoxOrders")
        self.gridLayout_2.addWidget(self.comboBoxOrders, 0, 3, 1, 1)
        self.lineEditProgName = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEditProgName.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditProgName.sizePolicy().hasHeightForWidth())
        self.lineEditProgName.setSizePolicy(sizePolicy)
        self.lineEditProgName.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditProgName.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEditProgName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditProgName.setInputMask("")
        self.lineEditProgName.setText("")
        self.lineEditProgName.setMaxLength(1)
        self.lineEditProgName.setCursorPosition(0)
        self.lineEditProgName.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditProgName.setObjectName("lineEditProgName")
        self.gridLayout_2.addWidget(self.lineEditProgName, 0, 5, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 0, 0, 1, 1)
        self.comboBoxPeriod = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxPeriod.sizePolicy().hasHeightForWidth())
        self.comboBoxPeriod.setSizePolicy(sizePolicy)
        self.comboBoxPeriod.setMinimumSize(QtCore.QSize(50, 30))
        self.comboBoxPeriod.setMaximumSize(QtCore.QSize(100, 30))
        self.comboBoxPeriod.setObjectName("comboBoxPeriod")
        self.gridLayout_2.addWidget(self.comboBoxPeriod, 0, 9, 1, 1)
        self.checkBoxSaveLog = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxSaveLog.sizePolicy().hasHeightForWidth())
        self.checkBoxSaveLog.setSizePolicy(sizePolicy)
        self.checkBoxSaveLog.setMinimumSize(QtCore.QSize(100, 0))
        self.checkBoxSaveLog.setObjectName("checkBoxSaveLog")
        self.gridLayout_2.addWidget(self.checkBoxSaveLog, 0, 11, 1, 1)
        self.BtnStart = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnStart.sizePolicy().hasHeightForWidth())
        self.BtnStart.setSizePolicy(sizePolicy)
        self.BtnStart.setMinimumSize(QtCore.QSize(100, 40))
        self.BtnStart.setMaximumSize(QtCore.QSize(100, 40))
        self.BtnStart.setObjectName("BtnStart")
        self.gridLayout_2.addWidget(self.BtnStart, 0, 13, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 0, 12, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 0, 4, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 0, 14, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 7, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 0, 8, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem12, 0, 10, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem13, 0, 6, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.comboBoxOrders.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PBoxTool"))
        self.BtnConnect.setText(_translate("MainWindow", "Connect"))
        self.labelIPAddr.setText(_translate("MainWindow", "Device IP address :"))
        self.label_2.setText(_translate("MainWindow", "Port:"))
        self.tableWidget.setSortingEnabled(False)
        self.labelModel.setText(_translate("MainWindow", "PBoxTool-Panasert(TCP) V1.0.3"))
        self.label_3.setText(_translate("MainWindow", "CMD:"))
        self.checkBoxSaveLog.setText(_translate("MainWindow", "Save Logs"))
        self.BtnStart.setText(_translate("MainWindow", "Start(&S)"))
        self.label_5.setText(_translate("MainWindow", "Period(s):"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

